### PR TITLE
UI Changes : New Location for Progress bar.

### PR DESCRIPTION
**Pull request by nikhilagrawaldotnet**
1. Made more space for links hover in statusbar - Moved Progress Bar below addressbar.
    a) Thinly visible when loading, hides when loaded.
    b) No flickering as progress bar and browser share same row.
2. Load page when hit Enter in Addressbar - Behaviour for that.
3. Refactor.

capture

### CODE REVIEW

**Comment by perlun** [comment]
@amaitland I think this supersedes #40 a bit, and would be fine with us merging this instead of the other one. What do you think about it?

**Comment by amaitland** [comment]
@perlun Sounds fine to me, I merged the changes into `cefsharp/63` with commit https://github.com/cefsharp/CefSharp.MinimalExample/commit/a923fe4d837a8419d5373616513e7d1d96729fd7 and have done some testing, fine so far.

**Comment by perlun** [comment]
@amaitland Alright, thanks. Do we merge it into master also or what's the suggested process?

**Comment by amaitland** [comment]
> Do we merge it into master also or what's the suggested process?

`cefsharp/63` will be merged into `master` when the official `63.0.0` packages are out, so it'll be taken care of then. If you want to merge directly into `master` now then by all means do so 😄

**Comment by perlun** [comment]
> cefsharp/63 will be merged into master when the official 63.0.0 packages are out, so it'll be taken care of then.

Ah, alright! I wasn't aware that this was what the process looked like. Thanks for the merge!

**Pull request merged**
